import streamlit as st
import streamlit.components.v1 as com
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.graph_objects as go
from streamlit_option_menu import option_menu
from tqdm import tqdm
import pages
import time
from datetime import date
import datetime
import requests
from sklearn.preprocessing import MinMaxScaler
st.set_page_config(page_title="Details",page_icon="icon.jpg",initial_sidebar_state="collapsed")
with open('style.css') as f:
    css = f.read()
st.markdown(f'<style>{css}</style>', unsafe_allow_html=True)
st.header("Details of the stock selected",divider='blue',)
background_image = """
<style>
[data-testid="stAppViewContainer"] > .main {
    background-image: url("https://images.pexels.com/photos/4593876/pexels-photo-4593876.jpeg?auto=compress&cs=tinysrgb&w=600");
    background-size: 100vw 100vh;  # This sets the size to cover 100% of the viewport width and height
    background-position: center;  
    background-repeat: no-repeat;

    }
</style>
"""
st.markdown(background_image, unsafe_allow_html=True)
st.markdown("""
<style>
    #MainMenu, header, footer {visibility: hidden;}

    /* This code gets the first element on the sidebar,
    and overrides its default styling */
    section[data-testid="stSidebar"] div:first-child {
        top: 0;
        height: 100vh;
    }
</style>
""",unsafe_allow_html=True)
st.markdown(
    """
<style>
    [data-testid="collapsedControl"] {
        display: none
    }
</style>
""",
    unsafe_allow_html=True,
)
ticker_list= ["ABL","ABOT","AGP","AICL","AIRLINK","AKBL","APL","ARPL","ATLH","ATRL","AVN","BAFL","BAHL","BNWM","BOP","CEPB","CNERGY","COLG","DAWH","DCR","DGKC","EFERT","EFUG","ENGRO","EPCL","FABL","FATIMA","FCCL","FCEPL","FFBL","FFC","FHAM","GADT","GATM","GHGL","GLAXO","HBL","HCAR","HGFA","HINOON","HMB","HUBC","IBFL","ILP","INDU","INIL","ISL","JDWS","JVDC","KAPCO","KEL","KOHC","KTML","LCI","LOTCHEM","LUCK","MARI","MCB","MEBL","MTL","MUGHAL","MUREB","NATF","NBP","NESTLE","NML","NRL","OGDC","PABC","PAEL","PAKT","PGLC","PIBTL","PIOC","POL","POML","PPL","PSEL","PSMC","PSO","PSX","PTC","RMPL","SCBPL","SEARL","SHEL","SHFA","SNGP","SRVI","SYS","TGL","THALL","TRG","UBL","UNITY","UPFL","YOUW"]
ticker=st.selectbox('Select the Company',ticker_list)
if ticker=="ABL":
    st.image('Images/ABL.png')
    st.write("Allied Bank is a leading financial institution known for its strong presence and reliable services. As one of the largest banks in Pakistan, it offers a comprehensive range of financial products and services to individuals and businesses.The bank provides traditional banking services such as savings and current accounts, fixed deposits, and loans. It also offers innovative solutions like online banking, mobile banking, and electronic fund transfers, ensuring convenient access to banking services.With an extensive network of branches and ATMs, Allied Bank prioritizes accessibility for its customers across the country. It has also established strategic partnerships with international banks, enabling seamless global transactions and trade finance services.Allied Bank is committed to delivering exceptional customer service and has made significant investments in technology to enhance its operations. The bank places a strong emphasis on security, implementing robust measures to safeguard customer information and prevent financial fraud.In addition to its focus on customer satisfaction, Allied Bank actively supports economic growth and development. It collaborates with businesses to provide tailored financial solutions and actively promotes financial inclusion by extending services to underserved communities.The bank also engages in corporate social responsibility initiatives, specifically in the areas of education, healthcare, and environmental sustainability. It aims to make a positive impact on society through its contributions to various social welfare programs.Overall, Allied Bank is a trusted financial institution with a rich history and modern banking services. Its extensive network, technological advancements, and customer-centric approach position it as a key player in the financial sector, contributing to the economic progress of its country and the well-being of its customers.")
if  ticker == "ABOT":
    st.image('Images/ABOT.png')
    st.write("Abbott Laboratories (Pak) Ltd. is a renowned pharmaceutical and healthcare company operating in Pakistan. As a subsidiary of Abbott Laboratories, a global healthcare organization, Abbott Laboratories (Pak) Ltd. is committed to improving the health and well-being of people through its innovative products and services. The company offers a diverse portfolio of pharmaceuticals, medical devices, diagnostics, and nutritional products. It focuses on areas such as cardiovascular health, diabetes care, infectious diseases, women's health, and nutritional supplements. Abbott Laboratories (Pak) Ltd. is known for its high-quality products that meet stringent international standards. The company's pharmaceutical division develops and markets a wide range of prescription drugs, catering to various therapeutic areas. It strives to introduce new and effective treatments to address unmet medical needs in the Pakistani market. Abbott Laboratories (Pak) Ltd. also specializes in medical devices and diagnostics, offering advanced technologies for healthcare professionals. Their product range includes devices for cardiovascular care, diabetes management, point-of-care testing, and laboratory diagnostics. These technologies aid in the accurate diagnosis, monitoring, and treatment of various medical conditions. Additionally, Abbott Laboratories (Pak) Ltd. is a prominent player in the field of nutrition, providing a comprehensive range of nutritional products for infants, children, and adults. These products are developed to support healthy growth, development, and overall well-being. The company is committed to maintaining the highest standards of quality, safety, and ethics. It adheres to strict regulatory guidelines and invests in research and development to continuously innovate and improve its offerings. Furthermore, Abbott Laboratories (Pak) Ltd. actively engages with healthcare professionals, institutions, and policymakers to promote medical education and awareness. It also collaborates with local communities to support initiatives related to healthcare access, education, and environmental sustainability. Overall, Abbott Laboratories (Pak) Ltd. is a trusted name in the pharmaceutical and healthcare industry in Pakistan. Through its diverse portfolio of products, commitment to quality, and focus on improving healthcare outcomes, the company plays a significant role in advancing the health and well-being of people in the country.")
if  ticker == "AGP":
    st.image('Images/AGP.png')
    st.write("Aspin Pharma Pvt Ltd is a prominent pharmaceutical company based in Pakistan. The company is dedicated to the development, manufacturing, and marketing of high-quality pharmaceutical products. With a focus on innovation and research, Aspin Pharma strives to provide effective and affordable healthcare solutions to patients. The company offers a diverse range of pharmaceutical products across various therapeutic areas, including cardiovascular health, respiratory disorders, gastrointestinal disorders, neurology, and dermatology. These products are developed in state-of-the-art manufacturing facilities, adhering to stringent quality standards and regulatory requirements. Aspin Pharma Pvt Ltd maintains a robust research and development division that continuously explores new drug formulations and technologies. This emphasis on innovation allows the company to introduce novel treatments and improve existing formulations to enhance patient outcomes. With a strong commitment to quality, safety, and ethical practices, Aspin Pharma Pvt Ltd has built a reputation for reliability and trustworthiness in the pharmaceutical industry in Pakistan.")
if  ticker == "AICL":
    st.image('Images/AICL.png')
    st.write("Adamjee Insurance is a leading insurance company in Pakistan, offering a comprehensive range of insurance products and services to individuals, businesses, and institutions. With a rich history and a focus on customer-centricity, Adamjee Insurance provides various types of insurance coverage, including motor insurance, health insurance, travel insurance, property insurance, marine insurance, and liability insurance. The company strong emphasis on prompt claim settlement, risk assessment, and ethical practices has contributed to its reputation as a trusted provider of reliable insurance solutions in Pakistan. Additionally, Adamjee Insurance actively engages in corporate social responsibility initiatives, demonstrating its commitment to community development and sustainability.")
if  ticker == "AIRLINK":
    st.image('Images/AIRLINK.png')
    st.write("Airlink is a technology company based in Pakistan that specializes in providing internet services, managed networking, and digital solutions. It was founded in 1996 and has since become one of the leading IT and communication service providers in the country. Airlink's services are used by both small businesses and large corporations, making it a key player in Pakistan's growing digital economy.In addition to its core services, Airlink also offers cloud solutions, cybersecurity, and data center services. The company's strong focus on innovation and customer satisfaction has helped it to maintain a competitive edge in the market. Airlink is known for its reliable and high-speed internet services, making it a top choice for businesses and individuals alike. With a nationwide presence and a strong commitment to technological advancement, Airlink continues to be a major player in Pakistan's rapidly evolving tech industry.")
if  ticker == "AKBL":
    st.image('Images/AKBL.png')
    st.write("Askari Bank is a leading commercial bank in Pakistan, offering a comprehensive range of financial products and services. With a strong presence and customer-centric approach, the bank provides personal banking solutions including deposit accounts, loans, and credit cards, as well as corporate banking services such as trade finance and treasury services. Askari Bank also operates an Islamic banking division, catering to customers seeking Sharia-compliant banking options. The bank prioritizes customer convenience through its extensive network of branches and advanced digital banking platforms. Committed to professionalism and ethical practices, Askari Bank actively contributes to social development through its corporate social responsibility initiatives. Overall, Askari Bank is a trusted financial institution in Pakistan, providing reliable banking services to individuals and businesses.")
if  ticker == "APL":
    st.image('Images/APL.png')
    st.write("Attock Petroleum is a prominent oil marketing company in Pakistan. It operates an extensive network of retail outlets across the country, offering a wide range of petroleum and related products. This includes various fuels such as gasoline, diesel, and LPG, as well as lubricants and specialty products. Attock Petroleum places a strong emphasis on quality, safety, and environmental responsibility, ensuring that its products comply with stringent standards. The company plays a vital role in meeting the energy needs of Pakistan and is committed to delivering reliable and efficient solutions to its customers.Attock petroleum limited (the company) was incorporated in pakistan as a public limited company on december 3, 1995 and it commenced its operations in 1998. The company was listed on karachi stock exchange on march 7, 2005. The registered office of the company is situated at attock house, morgah, rawalpindi, pakistan. The company is domiciled in islamabad. The principal activity of the company is procurement, storage and marketing of petroleum and related products. Pharaon investment group limited holding s.A.L holds 34.38% (as of june 30, 2011) shares of the company.")
if  ticker == "ARPL":
    st.write("Archroma Pakistan Limited (the Company) is a limited liability company, incorporated and domiciled in Pakistan. The Company is listed on Pakistan Stock Exchange Limited. The Company is a subsidiary of Archroma Textiles S.a.r.l., incorporated in Luxembourg, headquartered in Reinach, Switzerland which holds 75 percent of the share capital of the Company.The Company is primarily engaged in the manufacture, import and sale of chemicals, dyestuffs and coating, adhesive and sealants. It also acts as an indenting agent.Archroma is a global, diversified provider of dyes and specialty chemicals serving the branded and performance textiles, packaging and paper, and coatings, adhesives and sealants markets. The company operates a highly integrated, customer-focused platform that delivers specialized performance and color solutions in over 100 countries.Archroma works with 3,000 employees over 35 countries and with 26 production sites.")
if  ticker == "ATLH":
    st.image('Images/ATLH.png')
    st.write("Atlas Honda Limited is a public listed company which was incorporated on October 16, 1962. It is a joint collaboration between Honda Motor Company Limited Japan, the largest and most reputed motorcycle brand in the world, and Atlas Group, one of Pakistan’s most renowned business conglomerates. The Company is principally engaged in progressive manufacturing and marketing of motorcycles and spare parts.Atlas Honda Limited is the largest motorcycle manufacturer in Pakistan with the strongest brand value and highest customer loyalty. The Company is considered a pioneer of motorcycle industry in the country and has been leading two wheeler market successfully for over 50 years.The Company currently has a production capacity of over 1.5 million units per annum and continues to maintain its status as market leader both in terms of volume and quality. It also exports its motorcycles and spare parts to Bangladesh and Afghanistan.With highest quality products, state of the art manufacturing facilities, largest dealership network & impeccable after sales service, Atlas Honda Limited is today considered a benchmark for two wheeler manufacturing. It has been proudly and successfully fulfilling its role as the flag bearer of motorcycle industry in Pakistan.")
if  ticker == "ATRL":
    st.image('Images/ATRL.png')
    st.write("Attock Refinery Limited was incorporated in Pakistan on November 8, 1978 as a private limited company and was converted into a public company on June 26, 1979. It is principally engaged in the refining of crude oil. The Company is subsidiary of The Attock Oil Company Limited, England and its ultimate parent is Coral Holding Limited (a private limited company incorporated in Malta).")
if  ticker == "AVN":
    st.image('Images/AVN.png')
    st.write("Avanceon is the leading provider of industrial automation, process control and systems integration as well as proprietary energy management solutions and support services. It has a strong market footprint through its offices in Dubai, United Arab Emirates, covering the Middle East, Lahore, Pakistan, covering South East Asia, and Exton, Pennsylvania, covering North America. Avanceon has been in the automation business since 1984 and has transformed into a 360 degree solution provider for automation, energy management, service and maintenance for major blue chip companies. A certified member of the select group of Control System Integrators Association and is also listed on the Control Engineering Magazines System Integrator Hall of Fame.")
if  ticker == "BAFL":
    st.image('Images/BAFL.png')
    st.write("Bank Alfalah is one of the largest banks in Pakistan, with a network of over 1000 branches across more than 200 cities in the country, and international presence in Afghanistan, Bangladesh, Bahrain and the UAE. The Bank also has a representative office in Abu Dhabi. Bank Alfalah is owned and operated by the Abu Dhabi Group. Incorporated as a public limited company on 21st June, 1992 under the Companies Act, 2017, Bank Alfalah commenced its banking operations in the same year.The Bank provides financial solutions to consumers, corporations, institutions and governments through a broad spectrum of products and services, including corporate and investment banking, consumer banking and credit, securities brokerage, commercial, SME, agri finance, Islamic and asset financing solutions.VIS & PACRA have assigned an entity rating of AA+ (double A plus) for the long-term and A1+ (A one plus) for the short-term, with outlook assigned as stable. The Bank is listed on the Pakistan Stock Exchange.")
if  ticker == "BAHL":
    st.image('Images/BAHL.png')
    st.write("Bank AL Habib Limited (BAHL) is a prominent Pakistani bank that offers Islamic banking services. It was incorporated in 1991 and began operations in 1992. In 2004, BAHL obtained a license for Islamic banking and established an independent Islamic Banking Division (BAHL-IBD) in 2005. BAHL's Islamic Banking Division has over 130 branches, 150 Islamic windows, and covers more than 78 cities.")
if  ticker == "BNWM":
    st.image('Images/BNWM.png')
    st.write("Bannu Woollen Mill Ltd was established by PIDC in 1953 and as such is the oldest woolen industry of Pakistan. On disinvestments by PIDC in 1964, it was purchased by Bibo Jee Group of Companies founded by a renowned industrialist of the country Late Lt.Gen.(R)M. Habibullah Khan Khattak. This group of companies is engaged in the manufacture of a vast range of products, providing jobs to thousands of hands directly and many more indirectly through down-stream industries and is making considerable contribution to the National exchequer and the GDP.The mill was made a public limited company in 1992 and is quoted at Karachi/Islamabad Stock Exchanges.The company's quality management system has been certified and registered against ISO 9001-2000 standards by M/S Moody International Certification Ltd; with accreditation to M/S UKAS (U.K).The Mills manufactures a variety of woolen products which include tweed, blazer, velour, superior/donigal/honey shirting, byla & byma for light winter wear, blankets, shawls, services dress cloth, upholstery and curtain cloth etc. in attractive shades and designs.")
if  ticker == "BOP":
    st.image('Images/BOP.png')
    st.write("The Bank of Punjab (BOP) head quartered in BOP tower,  Main Boulevard Gulberg, Lahore is one of the prominent financial institution of the country with PACRA Ratings: AA+ Long Term and A1+ Short Term.The management of the bank has implemented strategies and policies to carve a distinct position in the market place. Fortified with years of banking expertise and driven by the strategic goals set out by our board of directors and senior management, the bank has invested in revolutionary technology to have an extensive range of products and services. This facilitates our commitment to repay the trust and confidence of our stakeholders, and also to a culture of innovation.BOP has emerged as one of the foremost financial institutions in the country, focused on spurring an economic revival by endeavoring to meet the needs of tomorrow as well as today. Our extensive portfolio encompasses all facets of banking.")
if  ticker == "CEPB":
    st.image('Images/CEPB.png')
    st.write("Century Paper & Board Mills Limited (CPBM) is part of Lakson Group of Companies Pakistan. The Lakson Group of Companies is one the leading groups of the country with diversified interests in industries such as Paper & Paperboard, Printing & Packaging, Soaps & Detergents, Instant Fruit Drinks, Fast Food Restaurant , Textiles, Surgical Goods, Information Technology, Insurance, Travel & Tours, Print & Electronic media, Investments and Software Development.Lakson Group of Companies has built up Strategic Business Relationships and Business Alliances with Multi National Corporations which includes Tetley Tea, Colgate-Palmolive, McDonalds and Kraft Foods.")
if  ticker == "CNERGY":
    st.image('Images/CNERGY.png')
    st.write("Cnergyico is one of the Pakistans leading petroleum company engaged in the businesses of oil refining, petroleum marketing, and petroleum logistics, headquartered in Karachi.Cnergyico Pk Limited is Pakistans largest refinery by capacity, having the nations highest refining capacity of 156,000 barrels per day. Cnergyico produces a wide range of refined petroleum products, including LPG, Motor Gasoline, Kerosene, Jet Fuel, High-speed Diesel, and Furnace Oil. The companys vision is to achieve sustainable productivity and deliver shareholder return while upholding high environmental, health, and safety standards.We take pride in having the largest capacity crude oil storage tanks in the country. Our petroleum distribution network facilitates the movement of petroleum products around the country, providing greater economies of scale. Today Cnergyico has more than 473 retail outlets nationwide and is growing by 35-40 outlets annually.Cnergyico is Pakistans largest vertically integrated oil refining company that fulfills the nations energy requirements and propels the countrys progress.We are using state-of-the-art equipment, advanced technology, and an innovative approach to produce energy products in a sustainable and environmentally friendly way.We own and operate high-quality energy assets that hold strategic importance in the countrys energy landscape, including Pakistans largest oil refinery in terms of nameplate capacity (i.e. 156,000 barrels of oil per day), a vast and rapidly growing network of retail outlets,")
if  ticker == "COLG":
    st.image('Images/COLG.png')
    st.write("Colgate-Palmolive Pakistan (COLG) is a Pakistani consumer goods company that manufactures and sells personal care, detergents, and home care products. It was founded in 1977 and is based in Karachi, Pakistan. COLG is a subsidiary of American multinational company Colgate-Palmolive and Pakistani company Lakson Group, with 40 percent shares.COLG's products include toothpaste, toothbrush, beauty soap, hand wash, shampoo, conditioner, laundry detergents, laundry bar, fabric conditioner, dishwash bar, dishwash liquid, dishwash paste, and diswash powder. COLG also manufactures soap and cleaning compounds, and brooms, brushes, and mops.")
if  ticker == "DAWH":
    st.image('Images/DAWH.png')
    st.write("Dawood Hercules Corporation Limited (DH Corp) is a publicly listed investment holding platform that manages investments in a variety of sectors, including its subsidiaries and associated companies. DH Corp was incorporated in Pakistan on April 17, 1968 as a joint venture between the Pakistani Dawood Group and the American company Hercules Inc. The company's main activity is to manage investments, including in its subsidiaries and associated companies.DH Corp's subsidiary, Engro Corporation Limited, is one of Pakistan's largest industrial conglomerates. ")
if  ticker == "DCR":
    st.image('Images/DCR.png')
    st.write(" Dolmen City REIT (DCR), Pakistan's first Real Estate Investment Trust (REIT). DCR was established in 2015 between Arif Habib Dolmen REIT Management Limited (AHDRML) and the Central Depositary Company of Pakistan Limited (CDCPL). DCR offers investors the opportunity to become unit holders of two components of the Dolmen City project: Dolmen Mall Clifton and The Harbor Front. Dolmen Mall Clifton is a shopping mall with approximately 130 retail outlets, including Mango, Next, Nike, Nine West, Timberland, and Charles & Keith.")
if  ticker == "DGKC":
    st.image('Images/DGKC.png')
    st.write("D.G. Khan Cement Company Limited (DGKCC) is a Pakistani cement manufacturer that was founded in 1978 and is headquartered in Lahore. It is one of the largest cement manufacturers in Pakistan, with a production capacity of 25,000 tons per day (7.500 million tons/annum). DGKCC has four cement plants, two in Dera Ghazi Khan, one in Khairpur Distt. Chakwal, and one in Hub Lasbela District (Balochistan). The plants use the latest Dry Process Technology and their production processes are environment friendly and comply with the World Bank's environmental standards.DGKCC is listed on Pakistan Stock Exchange and is blue chip stock. Its mission is to provide quality products to customers, explore new markets, and foster a sound and dynamic team.")
if  ticker == "EFERT":
    st.image('Images/EFERT.png')
    st.write("Engro Fertilizers Limited is a Pakistani company that manufactures, buys, and sells fertilizers, seeds, and pesticides. It also offers logistics services and is a subsidiary of the Engro Corporation conglomerate. Engro Fertilizers is one of the world's 50 largest fertilizer manufacturers, with a 30% market share in Pakistan. The company's products focus on crop nutrition and yield, and some of its brands include Engro Zarkhez, Zingro, Engro DAP, and Zabardast Urea. Engro Fertilizers also offers a farm advisory support system to help farmers access resources and advice for efficient farming.Engro Fertilizers operates in five segments: Urea, Phosphates, Specialty Fertilizers Business, Crop Sciences division, and E-logistics.")
if  ticker == "EFUG":
    st.image('Images/EFUG.png')
    st.write("Eastern Federal Union Insurance Company (EFU) is Pakistan's largest and oldest insurance company, established in 1932 by Ghulam Mohammad with financial assistance from the Aga Khan III and the Nawab of Bhopal. EFU offers a variety of insurance products and services.EFU has a branch network spread across the country to provide world class service locally. JCR VIS rates EFU as AA+ with stable outlook and EUROMONEY has adjudged EFU the Best Insurance Company of Pakistan.")
if  ticker == "ENGRO":
    st.image('Images/ENGRO.png')
    st.write("Envisioning value creation for a multitude of stakeholders, Engro has invested in a diverse portfolio of businesses across the verticals of energy and related infrastructure, agricultural outputs, petrochemicals and telecommunication infrastructure in over 50 years. Engro is committed to helping overcome Pakistan’s energy crisis by using the countrys resources, and strengthen the agri-food sector by equipping our farmers with the right tools and capabilities.Engro recognizes that social prosperity is imperative for business growth. Hence, every venture of Engro operates on an inclusive business growth ideology wherein its success is integrated with the development of society. Investing today for a better tomorrow for Pakistan is at the cornerstone of every business we venture into. It is this passion that fuels Engro to step into unchartered territories, bring sustainable solutions to the forefront, and become the leading provider of products and services in the energy, agricultural, chemicals, and nutrition sectors.From uplifting the agri-sector, to improving the food value chain, to providing sustainable energy solutions, Engro has left no stone unturned in its pursuit of uplifting the entire nation in a timespan of over 50 years.")
if  ticker == "EPCL":
    st.image('Images/EPCL.jpeg')
    st.write("Engro Polymer & Chemicals Limited (EPCL) is a Pakistani company that manufactures, markets, and distributes PVC resin and other chlor-vinyl products under the brand name SABZ. EPCL is the only manufacturer of PVC resin in Pakistan and the only fully integrated chlor-vinyl chemical complex in the country. EPCL also produces other chlor alkali products, including caustic soda, sodium hypochlorite, and hydrochloric acid.EPCL was founded in 1997 as Engro Asahi Polymer and Chemical Ltd, a joint venture between Engro Chemical (50%), Asahi Glass Company (30%), and Mitsubishi Corporation (20%). The company's name was changed to Engro Polymer & Chemicals Limited in 2006 after Asahi Glass divested from the business. In 2023, EPCL had a net income of Rs. 66 billion and more than 70 percent of the local market share.")
if  ticker == "FABL":
    st.image('Images/FABL.png')
    st.write("Faysal Bank Limited is a Pakistani Islamic bank that was founded in 1994 and is headquartered in Karachi. It offers a variety of banking services, including Islamic banking, consumer banking, business banking, savings, credit cards, and debit cards.Faysal Bank is a subsidiary of KSA Holdings, which is based in Karachi, Pakistan. It is named after Mohammed bin Faisal Al Saud, and shares are listed on the Pakistan Stock Exchange. As of January 2023, the bank has 700 Islamic banking branches across more than 270 cities.")
if  ticker == "FATIMA":
    st.image('Images/Fatima.png')
    st.write("Fatima Fertilizer Company Limited (FATIMA) is a Pakistani company that manufactures, buys, sells, imports, and exports fertilizers and chemicals. It was incorporated on December 24, 2003, as a joint venture between the Fatima Group and Arif Habib Group. The company's foundation stone was laid by Shaukat Aziz, the Prime Minister of Pakistan at the time. FATIMA has three production plants, located in Multan, Sheikhupura, and Sadiqabad. The company's fully integrated production facility produces two intermediate products, ammonia and nitric acid, and four final products. The plant has a rated capacity of 1.28 million tons and has been in commercial production since 2011.")
if  ticker == "FCCL":
    st.image('Images/FCCL.png')
    st.write("Fauji Cement Covmpany Limited (FCCL) is a Pakistani cement manufacturer that was established in 1992 and is the third largest producer of cement in the country. FCCL is known for its high-quality products and has been a major contributor to the local cement industry, providing employment and boosting the country's economic growth. FCCL is headquartered in Rawalpindi and operates two cement plant lines, one each from FLS Denmark and TKIS (Thyssen Krupp industrial solutions) Germany. The company's plant at Jhang Bahtar, Tehsil Fateh Jang, District Attock in the province of Punjab has an initial capacity of 945,000 tons per annum, which was expanded in 2005. FCCL is certified by ISO 45001;2818, EN ISO 9001;2015, ISO 50001;2018, ISO 45001;2018, and EN ISO 14001;2015.")
if  ticker == "FCEPL":
    st.image('Images/FCEPL.png')
    st.write("FrieslandCampina Engro Pakistan Limited (FCEPL) is a Pakistani dairy company that manufactures, processes, and markets frozen desserts and dairy products. It is a subsidiary of the Dutch multinational cooperative FrieslandCampina and is based in Karachi, Pakistan. FCEPL was formed in 2013 to bring global technology and expertise to Pakistan's dairy industry.FCEPL has two processing plants in Sukkur and Sahiwal, and a dairy farm in Nara (Sindh). The company's strategic location in Karachi allows it to serve the local market while also facilitating access to international markets.")
if  ticker == "FFBL":
    st.image('Images/FFBL.png')
    st.write("Fauji Fertilizer Bin Qasim Limited (FFBL) is a Pakistani company that manufactures chemical fertilizers for agriculture. It is the only manufacturer of DAP and granular urea in Pakistan. FFBL has its offices and manufacturing plants in Islamabad, Karachi, Pindi Bhattian, Thatta, Bhalwal, Casablanca, and Jorf Lasfar.FFBL was incorporated under Companies Ordinance 1984 and has a complex located at Port Qasim in Karachi. The complex cost $468 million to build and has an annual capacity of 670,000 metric tons of DAP. FFBL has been listed on the Pakistan Stock Exchange (PSX) since May 14, 1996, and its trade symbol is “FFBL”.")
if  ticker == "FFC":
    st.image('Images/FFC.png')
    st.write("Fauji Fertilizer Company Limited (FFC) is a company that manufactures, buys, and sells fertilizers and chemicals. FFC was established in 1978 as a joint venture between Fauji Foundation and Haldor Topsoe A/S of Denmark. FFC is Pakistan's largest urea manufacturer, with three urea plants that produce more than 2 million metric tons of urea annually. FFC also produces and distributes power through its subsidiary, FFC Energy Limited (FFCEL). ")
if  ticker == "FHAM":
    st.image('Images/FHAM.png')
    st.write("First Habib Modaraba (FHM) is a non-bank Islamic financial institution that began operations in Pakistan in March 1985. FHM is a leader in the Modaraba sector, which is known for promoting Islamic finance in Pakistan's financial services industry. FHM offers a variety of Islamic financial services, including Ijara, Morabaha, Diminishing Musharakah, Salam, and Istisna.FHM has a total equity base of over Rs 2.50 billion and an assets size of approximately Rs 3.50 billion. FHM has maintained an AA+ credit rating for several years. In September 2023, PACRA assigned FHM an AA+ rating for long-term and A1+ for short-term.")
if  ticker == "GADT":
    st.image('Images/GADT.png')
    st.write("Gadoon Textile Mills Limited (GTML) was incorporated in Pakistan on February 23, 1988 as a public limited company. The company's main activities include manufacturing and selling yarn and knitted bedding products, and producing and selling milk. GTML is one of Pakistan's largest spinning units, processing all types of cotton and manmade fibers. The company has manufacturing plants in Karachi and Gadoon Amazai.GTML is part of the Yunus Brothers Group (YBG), which was formed in 1962. Muhammad Sohail Tabba is the CEO of GTML.")
if  ticker == "GATM":
    st.image('Images/GATM.png')
    st.write("The story of textiles in the subcontinent is the story of Gul Ahmed. The group began trading in textiles in the early 1900s. The group entered the field of manufacturing with the establishment of today’s iconic name of Gul Ahmed Textile Mills Ltd in the year 1953. Since its listing on the Karachi Stock Exchange in 1970, the company has been making rapid progress and enjoying a leading position in the world of textiles.With an installed capacity of more than 51,840 spindles, 300 state-of-the-art weaving machines, and the most modern yarn dyeing, processing & stitching units, Gul Ahmed is a composite unit – making everything from cotton yarn to finished products. Gul Ahmed has its captive power plant comprising gas engines, gas & steam turbines, and backup diesel engines. Believing in playing its role in protecting the environment, Gul Ahmed has also set up a wastewater treatment plant to treat 100% of its effluent, bringing it to NEQS levels.Gul Ahmed is playing a vital role not only as a textile giant but has a strong presence in the retail business as well. The opening of its flagship store – Ideas by Gul Ahmed– marked the group’s entry into the retail business. Starting from Karachi, Gul Ahmed now has an extensive chain of more than 40 retail stores across the country, offering a diverse range of products from home accessories to fashion clothing. More than 50 years since its inception, the name Gul Ahmed is still globally synonymous with quality, innovation & reliability.")
if  ticker == "GHGL":
    st.image('Images/GHGL.png')
    st.write("Ghani Glass Limited (GHGL) is a Pakistani company that manufactures and sells glass containers and float glass. Imtiaz Ahmad Khan and Anwaar Ahmad Khan founded the company in 1992, and it is headquartered in Lahore, Pakistan. GHGL is a part of the Ghani Group, a well-known business house in South Asia. The group has over 50 years of experience in the local and international markets, especially in the glass sector. GHGL has seven modern glass plants in Pakistan that produce container glass, float glass, and value added glass, with an annual capacity of over 1,570 TPD.GHGL provides glass packaging for the food and beverages, and pharmaceuticals sectors. It is the leader in the glass products manufacturing business in Pakistan, with the largest production facilities and market share in the country. GHGL exports its production to 29 countries worldwide and works in close partnership with international holdings operating in Pakistan.")
if  ticker == "GLAXO":
    st.image('Images/GSK.png')
    st.write("GlaxoSmithKline Pakistan Limited (GSK PK) is a pharmaceutical company that was founded in 2001 and is headquartered in Karachi, Pakistan. It is a subsidiary of the British company GSK and is the largest pharmaceutical company in Pakistan. GSK PK has been providing medicines and vaccines to patients in Pakistan for over 70 years.GSK PK's research and development focuses on four therapeutic areas: Infectious diseases, HIV, Oncology, and Immunology.")
if  ticker == "HBL":
    st.image('Images/HBL.png')
    st.write("Habib Bank Limited (HBL) is Pakistan's largest bank, with over 1,750 branches and 2,200 ATMs globally. It was established in Bombay on August 25, 1941 by the Habib family. In 1947, Muhammad Ali Jinnah requested that HBL move its operations to Pakistan, making it the country's first commercial bank. HBL's first international branch opened in Colombo, Sri Lanka in 1951, and the HBL Plaza building began operations in Karachi in 1971. HBL was nationalized in 1974, and has a domestic market share of over 40%.HBL is the largest domestic multinational company in Pakistan by assets, and has consistently ranked as the top Pakistani company in the Forbes Global 2000. HBL offers a variety of services, including mobile banking, internet banking, finance, treasury services, and trade services.")
if  ticker == "HCAR":
    st.image('Images/HCAR.png')
    st.write("Honda Atlas Cars (Pakistan) Limited (HCAR) is a joint venture between Honda Motor Company Limited Japan and the Atlas Group of Companies in Pakistan. It was incorporated on November 4, 1992, and the first car rolled off the assembly line on May 26, 1994. The company is headquartered in Lahore, Pakistan, and has regional offices in Lahore, Karachi, and Islamabad. HCAR manufactures and sells Honda vehicles and spare parts. The company operates through two segments: Manufacturing and Trading. The Manufacturing segment offers locally manufactured cars and parts, while the Trading segment deals with the trade of completely built units and parts.")
if  ticker == "HGFA":
    st.image('Images/HGFA.png')
    st.write("The HBL Growth Fund is an open-end equity fund that is listed in Pakistan and managed by HBL Asset Management Limited. The fund's goal is to increase the wealth of its unit holders by investing in listed equities.The fund's investment objective is to provide consistent returns to its investors by actively investing in a mix of short, medium, and long-term securities issued or guaranteed by the Government of Pakistan.The fund was established under a Trust Deed, with HBL Asset Management Limited as the Management Company and Central Depository Company of Pakistan Limited as the Trustee. The Management Company of the Fund has been registered as a Non-Banking Finance Company (NBFC) under the NBFC Rules, 2003.")
if  ticker == "HINOON":
    st.image('Images/HINOON.png')
    st.write("Highnoon Laboratories Limited (HINOON) is a pharmaceutical company in Pakistan that was founded in 1984 and is headquartered in Lahore. The company's main activities are manufacturing, importing, selling, and marketing pharmaceutical and other consumer products. HINOON's products focus on areas such as the alimentary tract and metabolism, antihistamines, anti-infectives, cardiovascular, endocrine, hematology, musculoskeletal, nervous system, parasitology, respiratory, and urinary.HINOON's shares have been listed on the Pakistan Stock Exchange Limited since November 1994. As of December 31, 2022, the company had 41.884 million shares outstanding, held by 3,519 shareholders. The local general public is the largest shareholder category, with 40.86 percent of shares.")
if  ticker == "HMB":
    st.image('Images/HMB.png')
    st.write("Habib Metropolitan Bank Ltd. (HMB) is a public limited company in Pakistan that provides commercial banking and financial services. It was incorporated in 1992 and is a subsidiary of Habib Bank AG Zurich, which has operations in many countries. HMB operates through three segments: Trading & Sales, Retail Banking, and Commercial Banking. HMB operates through branch banking and electronic banking channels, including a mobile app, internet banking, and an IBAN generator.")
if  ticker == "HUBC":
    st.image('Images/HUBC.png')
    st.write("The Hub Power Company Limited (HUBCO) is Pakistan's first and largest Independent Power Producer (IPP), established in 1991. HUBCO's main activities include developing, owning, operating, and maintaining power stations. The company's 1,200 MW (net) oil-fired power station in Balochistan (Hub plant) generates about 6% of Pakistan's total electricity. HUBCO also generates, distributes, and sells power at other locations in Pakistan.HUBCO's combined installed power generation capacity is 3,581 MW. The company has four projects listed in the China-Pakistan Economic Corridor (CPEC): Thar Energy Limited, ThalNova Power Thar (Private) Limited, Sindh Engro Coal Mining Company, and China Power Hub Generation Company. ")
if  ticker == "IBFL":
    st.image('Images/IBFL.png')
    st.write("Ibrahim Fibres Limited (IFL) is a textile manufacturing company in Pakistan that produces and sells polyester staple fiber (PSF) and yarn. IFL is the largest producer of PSF in Pakistan and has four textile spinning plants and two power generation plants. The company's core values include respect for individuals, passion for sustainable growth, and continuous learning.IFL was incorporated in 1986 as a public limited company and is listed on the Pakistan stock exchange. In 2000, IFL merged with other Ibrahim Group manufacturing companies, including Ibrahim Textile Mills Limited, A. A. Textiles Limited, Zainab Textile Mills Limited, and Ibrahim Energy Limited. ")
if  ticker == "ILP":
    st.image('Images/ILP.png')
    st.write("Interloop Limited is a textile-based manufacturing company in Faisalabad, Pakistan that specializes in the production and sale of socks, leggings, denim, and yarn. They are the largest listed apparel company on the Pakistan Stock Exchange and one of the world's largest hosiery manufacturers, producing over 830 million pairs of socks annually. Interloop supplies their products to retailers such as Nike, Adidas, H&M, Puma, Levi's, Reebok, and Target.Interloop was incorporated in Pakistan on April 25, 1992 and publicly listed on the Pakistan Stock Exchange on April 5, 2019. They have manufacturing facilities in Pakistan and Sri Lanka, and a presence in the USA, the Netherlands, China, and Japan. ")
if  ticker == "INDU":
    st.image('Images/INDU.png')
    st.write("Indus Motor Company Limited (IMC), also known as Toyota Indus, is a Pakistani automobile manufacturer that manufactures and sells Toyota and Daihatsu vehicles. IMC is a joint venture between the House of Habib of Pakistan, Toyota Motor Corporation (TMC), and Toyota Tsusho Corporation (TTC) of Japan. It was incorporated in 1989 and is based in Karachi, Pakistan.IMC's production facilities are located in the Port Bin Qasim Industrial Zone near Karachi and cover more than 105 acres. IMC is the only manufacturing site in the world that produces both Toyota and Daihatsu brands. IMC's product line includes the Toyota Corolla, Toyota Hilux Single Cabin 4x2, and Daihatsu Cuore, as well as a wide range of imported vehicles.")
if  ticker == "INIL":
    st.image('Images/INIL.png')
    st.write("International Industries Limited (IIL) is Pakistan's largest manufacturer of steel and polymer pipes, with a manufacturing capacity of 817,000 tons annually. The company was incorporated in 1948 and is quoted on the Pakistan Stock Exchange. IIL's products include galvanized steel pipes, precision steel tubes, API line pipes, and polymer pipes and fittings. Their products are used in plumbing, sewerage, rain drainage, water transportation and filtration systems, and irrigation networks.IIL has two manufacturing facilities, one in Karachi and one in Sheikhupura, and exports to 60 countries across six continents, particularly in Australia, Canada, and Sri Lanka. The company has two wholly-owned subsidiaries, IIL Americas Inc. in Canada and IIL Australia Pty. Inc. in Australia.")
if  ticker == "ISL":
    st.image('Images/ISL.png')
    st.write("International Steels Limited (ISL) is Pakistan's largest flat steel manufacturer and exporter. ISL's primary activity is manufacturing cold rolled, galvanized, and color coated steel coils and sheets. ISL also offers a service center that shapes flat rolled steel into various forms for industrial and commercial applications.ISL's vision is to promote industrial development in Pakistan by investing in state of the art technology and redefining what it is to be “Made in Pakistan”")
if  ticker == "JDWS":
    st.image('Images/JDWS.png')
    st.write("JDW Sugar Mills Limited (JDWS) is a Pakistani company that produces and sells crystalline sugar, electricity, and manages corporate farms. It was incorporated on May 31, 1990 as a private limited company and converted into a public limited company on August 24, 1991. JDW is Pakistan's largest sugar producer, accounting for around 15–17 percent of the country's sugar production.JDW's primary location is at 17 Abid Majeed Road, Lahore Cantt., Lahore, Punjab 54000, PK. It also has locations at Mauza Sharin, Jamal Din Wali, Distt. Rahim Yar Khan., Punjab 64200, PK, and Machi Goth, Sadiqabad, Distt. Rahim Yar Khan, Punjab 64200, PK.")
if  ticker == "JVDC":
    st.image('Images/JVDC.png')
    st.write("Javedan Corporation Limited, located in Karachi, is a company focused on creating a model city called Naya Nazimabad. The company aims to improve the lives of its residents by providing education, healthcare, physical fitness, and employment opportunities. The project follows a live, work, and play concept, aiming to create a haven for a progressive middle class. The company's management, along with qualified human resources, is dedicated to realizing this vision. They believe that in addition to benefiting society, this new venture will generate additional income for the company and its shareholders.")
if  ticker == "KAPCO":
    st.image('Images/KAPCO.png')
    st.write("The Kot Addu Power Company Limited (KAPCO) was incorporated in Pakistan on April 25, 1996 as a public limited company. The company's main activities are to own, operate, and maintain a multi-fuel fired power plant in Kot Addu, Punjab, Pakistan. The plant has a nameplate capacity of 1,600 MW and is Pakistan's largest combined cycle power plant. KAPCO sells the electrical energy produced from its power plant to the Central Power Purchasing Agency (Guarantee) Limited (CPPA-G). KAPCO was originally a Public-Sector Power Project, but was converted into an IPP through privatization. The Pakistan Water and Power Development Authority (WAPDA) built the Kot Addu Power Plant in five phases between 1985 and 1996. The plant is located on the left bank of the River Indus, 90 kilometers northwest of Multan and 16 kilometers from Taunsa Barrage. It comprises of 10 multi fuel fired gas turbines and 5 steam turbines. ")
if  ticker == "KEL":
    st.image('Images/KEL.png')
    st.write("KEL, or K-Electric Limited, is an energy company in Pakistan that generates, transmits, and distributes electricity. It was founded in September 1913 and is headquartered in KE House, DHA, Karachi-75500. KEL's CEO is Syed Moonis Abdullah Alvi and its Chairman is Mark Gerard Skelton. KEL produces electricity from its own generation units with an installed capacity of 1875 MW. It also has arrangements with external power producers for around 1680 MW, including 1100 MW from the National Grid.")
if  ticker == "KOHC":
    st.image('Images/KOHC.png')
    st.write("Kohat Cement Company Limited (KOHC) is a Pakistani cement manufacturer that was incorporated in 1980. The company's products include ordinary portland grey cement and super white cement. KOHC is listed on the Stock Exchanges of Pakistan and has an annual capacity of 2.8 million tons of grey cement and 148.5 thousand tons of white cement. The company's registered office and factory are located in Kohat, while its head office is in Lahore. KOHC was originally incorporated as State Cement Company of Pakistan in 1980 with an annual capacity of around 30,000 tons. In 1992, the government privatized the company. KOHC has been consistently performing and expanding its capacity.")
if  ticker == "KTML":
    st.image('Images/KTML.png')
    st.write("Kohinoor Textile Mills Limited (KTM) is a Pakistani public limited company that manufactures yarn and cloth, processes and stitches cloth, and trades in textile products. The company was founded in 1953 and is headquartered in Lahore, Pakistan. KTM is one of Pakistan's largest vertically integrated textile operations, with over 1,800 employees and a 90-acre facility. KTM's products include: Curtains, Bed in a bag (BIAB), Bed linen sets, Embroidery coverlets and bed spreads, and Down proof.KTM has a global presence, cutting-edge technology, and a highly skilled workforce. The company's annual sales are $110 million, with a yearly capacity of 90 million meters and operations in 20 countries. ")
if  ticker == "LCI":
    st.image('Images/LCI.png')
    st.write("Lucky Core Industries Limited (LCI) is a Pakistani chemical company that manufactures a variety of products, including polyester, pharmaceuticals, agrochemicals, soda ash, and animal health products. LCI's mission is to improve lives through best-in-class solutions.LCI was previously known as ICI Pakistan Limited and was formerly the Khewra Soda Ash Company from 1944–1947. The company has evolved from a small trading concern with a single manufacturing unit into one of the country's more recognized industrial conglomerates. In 2012, the Yunus Brothers Group (YBG) acquired the company, which has since invested over PKR 34 billion and grown its bottom line from PKR 989 million to PKR 17,773 million.")
if  ticker == "LOTCHEM":
    st.image('Images/LOTCHEM.png')
    st.write("Lotte Chemical Pakistan Limited (LCPL) is a Pakistani company that manufactures and sells purified terephthalic acid (PTA). The company was founded in 1996 under the supervision of ICI and incorporated in 1998. LCPL is the largest producer and supplier of PTA in Pakistan and exports to Asia and the Middle East. The company's PTA plant is located at Port Qasim, Karachi and has a capacity to produce more than 500,000 tons of PTA annually.LCPL's PTA is a key raw material for Pakistan's textile and PET packaging industries. It is also the foundation of the polyester chain, which includes polyester staple fiber, filament yarn, and PET resin. LCPL's parent company, LOTTE, is one of Korea's largest conglomerates with over 20 businesses in 30 countries. ")
if  ticker == "LUCK":
    st.image('Images/LUCK.png')
    st.write("Lucky Cement Limited (LCL) is Pakistan's largest producer and exporter of cement and clinker. Abdul Razzak Tabba founded the company in 1993, and it began operations in 1996. LCL is the flagship company of Yunus Brothers Group (YBG) and is listed on the Pakistan Stock Exchange (PSX) and London Stock Exchange.LCL has production facilities in Karachi and Pezu, Khyber Pakhtunkhwa to meet the cement needs of the country's northern and southern regions. It also has a grinding plant in Basra, Iraq and a cement plant in Congo, making it the only Pakistani cement company with a global presence. In 2021, LCL made 970 export shipments with a total export value of $77,731,401, with its top export markets being Afghanistan, Pakistan, and Sri Lanka. ")
if  ticker == "MARI":
    st.image('Images/MARI.png')
    st.write("Mari Petroleum Company Limited (MPCL) is a Pakistani petroleum exploration and production company that was founded in 1984. MPCL is one of Pakistan's largest E&P companies, with a 23% market share as the country's second-largest gas producer. The company's products include oil, natural gas, condensate, and liquefied petroleum gas. MPCL's headquarters are located in Islamabad, Pakistan, and its shares are traded on all of Pakistan's stock exchanges. ")
if  ticker == "MCB":
    st.image('Images/MCB.png')
    st.write("MCB Bank is one of the oldest banks of Pakistan, incorporated in private sector in 1947. It was nationalized in 1974 and privatized in 1991. MCB Bank's major shareholding is owned by Nishat group, a prominent business conglomerate, having diversified interests in Textiles, Cement, Banking, Insurance, Power Generation, Hotel Business, Agriculture, Dairy, Auto Manufacturing and Paper Products.To enter into international capital markets, the Bank launched its Global Depositary Receipts (GDRs) in 2006. It was the first Pakistani Bank which had its GDRs listed on the London Stock Exchange. In 2008, the Bank entered into a strategic partnership with Maybank, Malaysia, which owns 18.78% stake in MCB through Maybank International Trust (Labuan) Berhad. In 2017, operations of NIB Bank were successfully amalgamated into and with MCB under a merger scheme. MCB is the first Pakistani Bank which incorporated a wholly owned Islamic Banking subsidiary, MCB Islamic Bank Limited, to meet requirements of a significant segment of society, for financial solutions that conform to Shariah rulings, and demonstrate our confidence in the potential of the Islamic Banking industry in the country.")
if  ticker == "MEBL":
    st.image('Images/MEBL.png')
    st.write("Meezan Bank is Pakistan's first and largest Islamic bank, founded in 1997 and commencing operations in 2002. The bank is headquartered in Karachi, Pakistan, and has over 1,000 branches in more than 320 cities across the country.Meezan Bank operates strictly under the principles of Islamic Shariah and is recognized for its product development capability, Islamic banking research, and advisory services. In 2023, the bank was recognized as the Best Bank of Pakistan for the third time at the Pakistan Banking Awards. Meezan Bank is Pakistan's first and largest dedicated Islamic bank with: A network of over 550 online branches across the country. First-ever Islamic commercial banking license by the State Bank of Pakistan. Recognition as 'Best Islamic Bank in Pakistan' by numerous local and international institutions.")
if  ticker == "MTL":
    st.image('Images/MTL.png')
    st.write("Millat Tractors Limited (MTL) was founded in 1964 as Rana Tractors and Equipment Limited in Lahore, Pakistan to import and market Massey Ferguson tractors. In 1965, the company established facilities in Karachi to assemble tractors from semi-knocked-down kits, and in 1967, operations were moved to Lahore. In 1972, the company was nationalized and began assembling and marketing tractors for the Pakistan Tractor Corporation (PTC). In 1980, the government decided to indigenize tractors, and MTL was tasked with this role in collaboration with Massey Ferguson. ")
if  ticker == "MUGHAL":
    st.image('Images/MUGHAL.png')
    st.write("Mughal Iron & Steel Industries Limited (MISIL) is a Pakistani company that manufactures and sells mild steel products. The company was founded in 1950 as Mughal Traders, which imported iron and steel products for local consumption. In 2010, the company was incorporated as MISIL and listed on the Karachi Stock Exchange in 2015. MISIL is one of Pakistan's largest manufacturers of structural steel products, with an annual melting capacity of 384,000 tons. The company's manufacturing plant is located in Lahore.MISIL's business activities include making billets of mild steel, spring steel, deformed bar, re-bar, cold twisted rebar, and a wide range of sections. The company's mission statement is To meet the expectations of our employees by providing opportunities for professional growth and personal welfare. ")
if  ticker == "MUREB":
    st.image('Images/MUREB.png')
    st.write("Murree Brewery Company Limited (PSX: MEREB) is a Pakistani multinational company that manufactures alcoholic and non-alcoholic beverages. The company was founded in 1860 by the British in response to the increasing demand for beer by the British Raj personnel. It is Pakistan's largest and oldest producer of alcoholic products.The company's products are exported to India and Bangladesh. In 2014, the company established a flagship store on Park Avenue, in Manhattan, New York City. In 2013, Forbes named it one of Asia's 200 best companies.The company's fiscal year is July-June. In 2023, the company's revenue was $65.16, gross profit was $12.28, operating income was $5.57, income before tax was $7.45, and net income was $4.46.")
if  ticker == "NATF":
    st.image('Images/NATF.png')
    st.write("National Foods Limited (NFL) is a Pakistani food and beverage manufacturing company that was founded in 1970 by Waqar Hasan and Abdul Majeed. The company is headquartered in Karachi, Pakistan and operates in the local, United Arab Emirates, and Afghanistan markets. NFL started as a spice company but has since expanded into a versatile food company with over 250 products for the domestic market and over 100 different products for the international markets. NFL's products include spices, pickles, ketchup, jams, jellies, sauces, cooking pastes, rice, salt, juices, and ready-to-eat meals.NFL's vision is to create food that enriches the lives of people everywhere. Their products are purpose-made for convenience and easy preparation to match contemporary lifestyles, retain their values, and traditional tastes. NFL's primary location is 12/CL-6, Claremont Road, Civil Lines, Karachi, Sind 75530, PK. Their office A-13 is located at North Western Industrial Zone, Bin Qasim, Karachi, Sind 75020, PK. Their factory office is located at F- 160/ C, F- 133, S.I.T.E., Karachi, Sind 75000, PK. ")
if  ticker == "NBP":
    st.image('Images/NBP.png')
    st.write("The National Bank of Pakistan (NBP) is a government-owned multinational commercial bank that was established in 1949 to address Pakistan's economic crises after independence and reduce reliance on the Reserve Bank of India. The NBP is headquartered in Karachi and has over 1,500 branches across Pakistan and 22 overseas branches and offices. The NBP's products include loans, savings, consumer banking, corporate banking, and investment banking. Its services include debt-equity market, corporate investment banking, retail and consumer banking, agricultural financing, and treasury services. The NBP's major objective is to safeguard the stability of the financial system. As part of its supervisory and regulatory functions, the NBP oversees the liquidity, efficiency, and security of the payment system. It also contributes to the development of a secure infrastructure of the financial market. The NBP's vision is to be recognized as a leader and a brand synonymous with trust, highest standards of service quality, international best practices, and social responsibility. ")
if  ticker == "NESTLE":
    st.image('Images/NESTLE.png')
    st.write("Nestlé Pakistan Limited is a food and beverages company that has been serving Pakistani consumers since 1988. It is a subsidiary of the Switzerland-based Nestlé S.A. and is headquartered in Lahore. Nestlé Pakistan has four production facilities across the country, including two multi-product factories in Sheikhupura and Kabirwala, and one factory each in Islamabad and Karachi that produces bottled water. Nestlé Pakistan's mission is to enhance quality of life and contribute to a healthier future. The company's global ideology of Nutrition, Health and Wellness is inspired by the scientific breakthrough of its founder, Henri Nestlé, who invented the first infant food in 1867. ") 
if  ticker == "NML":
    st.image('Images/NML.png')
    st.write("Nishat Mills Limited (NML) is a public limited company that was established in 1951 and is the flagship company of Nishat Group, Pakistan's largest group. NML is one of Pakistan's largest and most modern vertically integrated textile companies. The company's production facilities include spinning, weaving, processing, stitching, and power generation. NML's products include ready-made curtains, bed linen, towels, and technical textiles for the contract business. NML's registered office is located at 53-A, Lawrence Road, Lahore. The company's total export for 2022 was Rs. 75.102 billion (US$ 422.215 million). In 2023, NML's revenue was $949.5M, with a 16.9 percent increase from 2022. ")
if  ticker == "NRL":
    st.image('Images/NRL.png')
    st.write("National Refinery Limited (NRL) is a public limited company that was incorporated in Pakistan on August 19, 1963. The company manufactures, produces, and sells a wide range of petroleum products. NRL's refinery complex has three refineries, including two lube refineries and one fuel refinery.The Government of Pakistan took over management of NRL in 1972 under the Economic Reforms Order. In November 1998, the Government of Pakistan placed NRL under the administrative control of the Ministry of Petroleum & Natural Resources. On July 7, 2005, the (Attock) Pharaon Group took over management of the company from the Government of Pakistan. ")
if  ticker == "OGDC":
    st.image('Images/OGDC.png')
    st.write("Oil & Gas Development Company Limited (OGDCL) is a Pakistani oil and gas company that explores, drills, refines, and sells oil and gas. The company was established in 1961 by the Government of Pakistan and became a public listed company in 1997. OGDCL is the largest E&P company in Pakistan and has the most extensive exploration acreage in the country. Its assets are located in the provinces of Sindh, Punjab, Balochistan, and Khyber Pakhtunkhwa (KPK).As of June 30, 2016, the Government of Pakistan owned 74.97 percent of OGDCL's shares, with the remainder held by private investors.")
if  ticker == "PABC":
    st.image('Images/PABC.jpeg')
    st.write("Pakistan Aluminium Beverage Cans Limited (PABC) is Pakistan's only local manufacturer of aluminum beverage cans. The company was established in December 2014 as a project of the Ashmore Investment Group UK, and began commercial operations in September 2017. PABC's plant is located at M-3 Industrial City in Faisalabad, and its corporate office is also in Faisalabad.PABC has a production capacity of 700 million cans per year, which can be expanded to 1.2 billion cans per year. The company's markets include Pakistan, Afghanistan, Bangladesh, and other countries in Southwest Asia.PABC's strategic management shifts have disrupted the monopoly of its competitors, leading to sustained growth and improved financial performance. ")
if  ticker == "PAEL":
    st.image('Images/PAEL.png')
    st.write("Pak Elektron Limited (PEL) (PSX: PAEL) is a Pakistani engineering corporation that manufactures home appliances and electrical equipment. It was established in 1956 in collaboration with AEG of Germany and is headquartered in Lahore, Punjab, Pakistan.Refrigerators, Air conditioners, Microwave ovens, Water dispensers, Transformers, Switchgear, and Energy meters. PEL has formed alliances with several international giants, including General Electric, Fujitsu, and Hitachi. The company has a 22% market share and sources its revenue from two divisions: Power (33%) and Home Appliances (67 percent). ")
if  ticker == "PAKT":
    st.image('Images/PAKT.png')
    st.write("Pakistan Tobacco Company Limited (PTC) is a Pakistani cigarette manufacturer and subsidiary of British American Tobacco (BAT). It was incorporated in 1947, shortly after the partition of India, and took over the business of the Imperial Tobacco Company of India. PTC is Pakistan's largest cigarette maker, with two factories in Akora Khattak and Jhelum. Its brands include Dunhill, Benson and Hedges, John Player Gold Leaf, Capstan by Pall Mall, Gold Flake, and Embassy. PTC's vision is to be the First Choice for Everyone. The company's business principles include Responsible Product Stewardship, which means developing, manufacturing, and marketing products responsibly. PTC also aims to develop tobacco products that scientific and regulatory authorities recognize as posing substantially reduced health risks.PTC's managing director and CEO is Nicholas Stewart Hales, and its finance director is Mobasher Raza.")
if  ticker == "PGLC":
    st.image('Images/PGLC.png')
    st.write("Pak-Gulf Leasing Company Limited (PGLC) is a public limited company that provides finance leasing services in Pakistan. It was incorporated on December 27, 1994 and began operations on September 16, 1996. The company is listed on the Pakistan Stock Exchange and operates in two segments: Lease Finance and Vehicle Finance. PGLC offers Ijarah, diminishing musharakah, and auto-finance services. ")
if  ticker == "PIBTL":
    st.image('Images/PIBTL.png')
    st.write("Pakistan International Bulk Terminal Limited (PIBT) is Pakistan's first terminal for handling coal, clinker, and cement on a build, operate, and transfer (BOT) basis at Port Qasim Authority. PIBT is located at Port Qasim, which is 50 kilometers from Karachi on the Arabian Sea coastline. The terminal has a capacity to handle up to 12 million tons of coal and 4 million tons of cement and clinker per year, which can be increased to 20 million tons per year. PIBT uses rail, road, and sea networks to handle and deliver coal to power, cement, and other coal-based plants.PIBT has been setup as the Country's first terminal for handling Coal, Clinker and Cement on build, operate and transfer (BOT) basis at Port Qasim Authority. Port Qasim is located Fifty Kilometres from Karachi, on the coast line of the Arabian Sea.")
if  ticker == "PIOC":
    st.image('Images/PIOC.png')
    st.write("Pioneer Cement Limited (PCL) is a public company in Pakistan that manufactures and sells cement and clinker. It was incorporated on February 9, 1986 and is located in the Chenki district near Sargodha, Punjab. PCL's products include Ordinary Portland Cement (OPC) and Sulphate Resistant Cement (SRC). OPC is commonly used for structural work and concrete construction, while SRC is used in areas with sulfate salts, such as soil or saline water. PCL's production capacity has increased over the years, starting at 2,000 tons of clinker per day in 1986, increasing to 2,350 tons per day in 2005, and 4,300 tons per day in 2006. The company also has a brownfield cement production line with a capacity of nearly 8,000 tons per day and a waste heat recovery plant. ")
if  ticker == "POL":
    st.image('Images/POL.png')
    st.write("Pakistan Oilfields Limited (POL) is a public company that explores, drills, and produces crude oil and gas in Pakistan. It was incorporated on November 25, 1950, and is a subsidiary of the UK-based Attock Oil Company (AOC). POL is listed on all three stock exchanges in Pakistan and trades as PSX: POL. Its headquarters are in Rawalpindi, Punjab Province, Pakistan.In 2023, POL had a revenue of Rs. 60.95 billion (US$210 million), an operating income of Rs. 49.65 billion (US$170 million), and a net income of Rs. 13.20 billion (US$46 million). Shoaib A. Malik is the Chairman and CEO of POL. ")
if  ticker == "POML":
    st.image('Images/POML.png')
    st.write("Punjab Oil Mills Limited (POML) is a Pakistani company that manufactures and sells edible oils, fats, ghee, cooking oil, laundry soap, coffee, and mushrooms. The company was established in 1981 as a public limited company and is based in Islamabad, Pakistan. Their products are sold under the brand names Zaiqa®, CanOlive®, Ella®, and Oliva®.")
if  ticker == "PPL":
    st.image('Images/PPL.png')
    st.write("Pakistan Petroleum Limited (PPL) is an upstream and midstream oil and gas company that explores, develops, and produces crude oil, natural gas, Natural Gas Liquid (NGL), and Liquefied Petroleum Gas (LPG). PPL has been a leader in the energy sector since the mid-1950s and is a major supplier of natural gas, contributing about 20 percent of the country's total natural gas supplies. PPL operates 12 producing fields across the country, including Sui, Pakistan's largest gas field, and holds working interest in 18 partner-operated fields. PPL also has operations in exploration assets in Iraq and Yemen.PPL was incorporated on June 5, 1950, when it inherited the assets and liabilities of the Burmah Oil Company Ltd. In 1997, the former company sold all its remaining equity in PPL to the Government of Pakistan. As of June 2011, the Government of Pakistan held 70.66 percent of the shares.")
if  ticker == "PSEL":
    st.image('Images/PSEL.png')
    st.write("Pakistan Services Limited (PSL) is a public limited company that was incorporated in Karachi in 1958 by the Government of Pakistan and Pakistan International Airlines. The company's primary business is the hotel industry, and it owns and operates the Pearl Continental Hotels chain, which includes six hotels across Pakistan. The hotels are located in Karachi, Lahore, Rawalpindi, Malam Jabba, Bhurban, and Muzaffarabad, and have 1,445 rooms.PSL's statement of ethics states that the company is an equal opportunity employer, and that its recruitment and promotional policies are merit-based and free of gender bias. The company also recognizes and rewards employees for their specialized knowledge, intellectual skills, and qualifications.")
if  ticker == "PSMC":
    st.image('Images/PSMC.png')
    st.write("Pak Suzuki Motor Company Limited (PSMCL) was established in August 1983 as a joint venture between the Government of Pakistan and Suzuki Motor Corporation (SMC) of Japan. The company started commercial operations in January 1984 and was privatized in September 1992. PSMCL is Pakistan's leading automobile manufacturing company, producing, assembling, and marketing Suzuki brand vehicles and motorcycles. As of April 2016, PSMCL had over 50% market share and a virtual monopoly in the small car market.PSMCL's vision is to be recognized as a leading organization that values customers' needs and provides motoring solutions with strong customer care.")
if  ticker == "PSO":
    st.image('Images/PSO.png')
    st.write("Pakistan State Oil (PSO) is Pakistan's largest energy company, importing, storing, marketing, and distributing petroleum products. PSO's products include motor gasoline, diesel, furnace oil, jet fuel, liquefied petroleum gas, compressed natural gas, black oil, white oil, and lubricants. PSO has over 3,500 retail outlets, 9 installations, 19 depots, and refueling facilities at 10 airports and 2 seaports across Pakistan. PSO also has 2 lubricant manufacturing facilities and LPG storage and bottling facilities.PSO was founded on January 1, 1974, and became PSO on December 30, 1976, when the government merged Premier Oil Company Limited (POCL) and State Oil Company Limited (SOCL). PSO has a 78.2 percent share of the Black Oil market and a 54.3 percent share of the White Oil market.")
if  ticker == "PSX":
    st.image('Images/PSX.png')
    st.write("The Pakistan Stock Exchange (PSX) was established on September 18, 1947, and formally incorporated on March 10, 1949, as the Karachi Stock Exchange (Guarantee) Limited (KSE). In 2016, the PSX was formed by merging the Karachi, Lahore, and Islamabad Stock Exchanges. The PSX is a digitized marketplace where investors can buy and sell common stocks and other securities of listed companies. The PSX has about 375 companies listed, with a total market capitalization of PKR 7,756 billion (US$27 billion) as of January 2022. The exchange also has 1,886 foreign institutional investors, 883 domestic institutional investors, and about 220,000 retail investors.")
if  ticker == "PTC":
    st.image('Images/PTCL.png')
    st.write("Pakistan Telecommunication Company Limited (PTCL) is Pakistan's national telecommunications company, providing internet and telephone services across the country. PTCL was founded in 1947 as a telephone and telegraph department and has since grown into the largest integrated information communications company in Pakistan, with over 17,000 employees. PTCL offers a wide range of services.Pakistan Telecommunication Company Limited (PTCL) is Pakistan's national telecommunications company, providing internet and telephone services across the country. PTCL was founded in 1947 as a telephone and telegraph department and has since grown into the largest integrated information communications company in Pakistan, with over 17,000 employees. PTCL offers a wide range of services.")
if  ticker == "RMPL":
    st.image('Images/RMPL.png')
    st.write("Rafhan Maize Products Company Limited (RMPL) is a Pakistani company that produces and supplies food ingredients and industrial products. The company was founded in 1953 as a corn refining industry and is headquartered in Faisalabad, Pakistan. RMPL processes thousands of tons of corn annually to produce industrial starches, liquid glucose, dextrose, dextrin, and gluten meals. These products are supplied to the textiles, pharmaceuticals, paper, food, baking, confectionery, and other industries.RMPL's competitors include Barilla Gida, Schreiber Foods, Ventura Foods, and J-OIL MILLS. ")
if  ticker == "SCBPL":
    st.image('Images/SCBPL.png')
    st.write("Standard Chartered Bank (Pakistan) Limited was incorporated in Pakistan on 19 July 2006 and was granted approval for commencement of banking business by State Bank of Pakistan, with effect from 30 December 2006. The ultimate holding company of the Bank is Standard Chartered Plc., incorporated in England. The Bank is engaged in the banking business as defined in the Banking Companies Ordinance, 1962.")
if  ticker == "SEARL":
    st.image("Images/SEARL.png")
    st.write("The Searle Company Limited (TSCL) is a pharmaceutical company in Pakistan that manufactures and sells consumer health and nutritional products. The company was incorporated in 1965 as a subsidiary of G.D. Searle & Co., U.S.A. and became a public limited company in 1993. TSCL has two manufacturing facilities in Lahore and Karachi, Pakistan, and has strategic alliances with international companies like Organon, Schering Plough, MSD, Vifor, and Santen.")
if  ticker == "SHEL":
    st.image('Images/SHEL.png')
    st.write("Shell Pakistan Limited (SPL) is a Pakistani oil and gas company that has been in the South Asian region for over 100 years. It is a subsidiary of Shell plc, a British multinational oil and gas company headquartered in London. SPL is listed on the Pakistan Stock Exchange Limited and has a registered office at Shell House, 6, Ch. Khaliquzzaman Road, Karachi-75530, Pakistan. SPL has a network of over 600 sites, countrywide storage facilities, and a broad portfolio of global lubricant brands. It markets petroleum products and compressed natural gas, and blends and markets various kinds of lubricating oils. SPL's interests include downstream businesses such as retail, lubricants, and aviation.")
if  ticker == "SHFA":
    st.image('Images/SHFA.png')
    st.write("Shifa International Hospital (SIH) is a 550-bed, private, multi-specialty, tertiary care hospital in Islamabad, Pakistan. It offers comprehensive diagnostic and treatment services in more than 35 clinical specialties, including:Dermatology, Endocrinology, Nephrology, Neurology, Urology, Plastic Surgery, Orthopedics, and Pediatrics. SIH also provides organ transplant services, critical care and emergency services, and the latest medical technologies. The hospital is accredited by the Joint Commission International (JCI), which demonstrates its commitment to quality and patient safety.")
if  ticker == "SNGP":
    st.image('Images/SNGP.png')
    st.write("Sui Northern Gas Pipelines Limited (SNGPL) is a public limited company in Pakistan that buys, transmits, distributes, and supplies natural gas. It was incorporated in 1963 as a private limited company and converted to a public limited company in 1964 under the Companies Act 1913. SNGPL is listed on the Pakistan Stock Exchange and trades as PSX: SNGP. SNGPL is the largest integrated gas company in North Central Pakistan, serving more than 7.23 million consumers in Punjab, Khyber Pakhtunkhwa, and Azad Jammu & Kashmir. The company's headquarters are located in Lahore, Pakistan.")
if  ticker == "SRVI":
    st.image('Images/SRVI.jpeg')
    st.write("Service Industries Limited (SIL) or SRVI.PK is a global company that manufactures and sells footwear, tires, tubes, and technical rubber products. The company was founded in 1953 by Nazar Muhammad, Muhammad Hussain, and Muhammad Saeed, and is headquartered in Lahore, Pakistan. SIL has been Pakistan's largest footwear exporter for the past 10 years and is a pioneer in tire and tube manufacturing in the country.")
if  ticker == "SYS":
    st.image('Images/SYS.png')
    st.write("Systems Limited (SYS) is a Pakistani multinational public technology company that provides business process outsourcing (BPO) services and information technology (IT) solutions. The company was founded in 1977 by Aezaz Hussain and is headquartered in Lahore, Pakistan. As of June 2023, SYS has a market capitalization of around US\$441 million and is one of the largest IT exporters listed on the Pakistan Stock Exchange (PSX).SYS operates in North America, Europe, the Middle East, and Pakistan, and provides computing strategies and solutions to government and private organizations. The company has over 9,000 client-focused employees globally. ")
if  ticker == "TGL":
    st.image('Images/TGL.png')
    st.write("Tariq Glass Industries Limited (TGL) is a Pakistan-based company that manufactures and sells glass containers, tableware, float glass, and opal glass. The company was incorporated in 1978 as a private limited company and converted into a public limited company in 1980. TGL's shares are listed on the Pakistan Stock Exchange.TGL's brands include Toyo Nasic, Omroc, Nova, Rockware, Gemware, and Tariq Float glass. The company's tableware includes ashtrays, cake sets, jugs, plates and bowls, stemware, ice cream cups, and tumblers. TGL's production facilities are located at 33KM Lahore Sheikhupura Road, Sheikhupura, Punjab.")
if  ticker == "THALL":
    st.image('Images/THAL.png')
    st.write("Thal Limited (THAL) is a Pakistani conglomerate that was incorporated in 1966 as Thal Jute Mills Limited and began commercial production in 1969. The company's name was changed to Thal Limited in 2004, and in 2006, Pakistan Papersack Corporation Limited and Khyber Papers (Pvt.) Limited merged into Thal Limited.THAL is a diversified company that manufactures engineering products, jute products, paper sacks, and laminate products. The company's engineering segment manufactures automotive parts such as radiators, car air-conditioners, wiring systems, and engine components. The building material and allied product segment oversees the jute, papersack, and laminate operations. ")
if  ticker == "TRG":
    st.image('Images/TRG.png')
    st.write("The Resource Group Pakistan (TRG Pakistan) is a public venture capital company that invests in business process outsourcing and technology companies. Founded in 2002 by Zia Chishti, TRG Pakistan is headquartered in Karachi, Pakistan. TRG Pakistan's core philosophy is to invest today for a better tomorrow for Pakistan. Every TRG venture follows an inclusive growth model, integrating success with societal development. TRG Pakistan's vision is to be the global leader in providing business process outsourcing services. Their mission is to be the most efficient provider of business process outsourcing services by setting the industry standards for cost and quality services.")
if  ticker == "UBL":
    st.image('Images/UBL.png')
    st.write("United Bank Limited (UBL) is a Pakistani multinational commercial bank that was founded in 1958 by Agha Hasan Abedi and is based in Karachi. It is Pakistan's largest private sector bank, with over 1,390 branches nationwide, 18 overseas branches, and a significant presence in the Middle East. UBL also has representative offices in Beijing and Kazakhstan.UBL's first branch opened in Pakistan on November 7, 1959, at I.I. Chundrigar. In 1963, UBL became the first Pakistani bank to open a branch in London, and in 1967, it entered the UAE. In 2017, UBL was named Pakistan's Best Bank for Corporate Finance & Capital Market Development at the Pakistan Banking Awards.")
if  ticker == "UNITY":
    st.image('Images/UNITY.png')
    st.write("Unity Foods Limited (PSX: UNITY) is a public limited company in Pakistan that was incorporated in 1991 as Taha Spinning Mills. The company's main business is edible oil extraction, refining, and related businesses, but it also produces staples like flour, rice, lentils, and pulses, as well as industrial fats and feed ingredients for livestock and poultry. Unity Foods' registered office is located at Unity Tower, Plot # 8 C, Block-6, P.E.C.H.S., Karachi 75400.")
if  ticker == "UPFL":
    st.image('Images/UPFL.png')
    st.write("Unilever Pakistan Foods Limited (UPFL) is a Pakistan-based company that manufactures and sells consumer and commercial food products. The company was founded in 1948 in Rahim Yar Khan, Pakistan as a vegetable oil factory. It is now the largest fast-moving consumer goods company in Pakistan and one of the largest multinationals operating in the country. UPFL is headquartered in Karachi, Pakistan and has six factories located around Pakistan.UPFL sells products under the brand names of Rafhan, Knorr, Energile, Glaxose-D, Food Solutions, and Hellmann's. The company also manufactures and markets home and personal care products, beverages, and ice cream. ")
if  ticker == "YOUW":
    st.image('Images/YOUW.png')
    st.write("Yousaf Weaving Mills Limited (YWML) is a public limited company in Pakistan that was incorporated on January 17, 1988. The company is a leading manufacturer of textile products in Pakistan, specializing in textile spinning, weaving, and the sale of fabric. YWML also offers textiles, yarns, and synthetic fibers, and sells processed fabrics. The company has grown from a weaving unit to a composite textile unit with expansion in the dairy and agriculture sectors.YWML's production facilities are located on Multan Road in Pattoki, and its corporate office is located at 7/1 E-3 Main Boulevard, Gulberg III, Lahore, Pakistan. The company is a member of the All Pakistan Textile Mills Association and Lahore Chamber of Commerce and Industry.")
button_selected=st.button("GO Back to Main Page")
if button_selected:
    st.switch_page("app.py")
